### ISSUE TITLE
Feature request: support for cmd.exe console

### ISSUE THREAD

**Issue by piula** [Warfley/LazTermUtils#2]
Hello,

as you state, this package only works with Windows Terminal of Win10. It would, however, be incredibly useful if the classic Windows console which is provided by cmd.exe/conhost.exe could be supported as well.

Even some basic support (i.e. without colors or other fancy things, just cursor positioning and writing) would be welcome. :)

**Comment by Warfley** [comment]
This works with the standard windows console (cmd.exe) it just requires a current version of Windows 10.

I will not provide support for older versions of Windows, because I don't want to do like twice the effort just for supporting outdated  systems like Windows 7 or something like that
