### ISSUE TITLE
TTerminal object appears to be leaking memory

### ISSUE THREAD

**Issue by D3sdu** [Warfley/LazTermUtils#3]
Hello and thank you for this great project!

Just wanted to report that TTerminal objects don't appear to be freeing up all allocated memory. Sample code below compiled with "fpc -gh".

`
program LazTermUtilsExample;

{$MODE OBJFPC} {$LONGSTRINGS ON}

uses Terminal;

var
  term     : TTerminal;

begin
  term := TTerminal.create;
  term.free;
end.
`

Output:

$ ./LazTermUtilsExample

Heap dump by heaptrc unit of /tmp/LazTermUtilsExample
33 memory blocks allocated : 2689/2704
32 memory blocks freed     : 2649/2664
1 unfreed memory blocks : 40
True heap size : 393216
True free heap : 392960
Should be : 392984
Call trace for block $00007FB50F0F7200 size 40
  $0000000000498C3B
  $000000000048156F
  $0000000000429B17
  $00000000004295AA
  $00000000004010B2

Thanks!

**Comment by Warfley** [comment]
Fixed

**Comment by D3sdu** [comment]
Beautiful! Thank you very much :+1:
